services:
  - type: web
    name: discord-ai-api
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: HF_TOKEN
        value: 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
